language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-23.0.2
    - android-23
    
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-21